### ISSUE TITLE
Wrong output with basic usage

### ISSUE THREAD

**Issue by afbora** [hananils/kirby-tree-methods#1]
Content:

````
----

Text:

# My first headline

## My second headline

----
````

Template:
````php
<?= $page->text()->toTree()->level(3) ?>
````

Output:
````html
<p>
# My first headline

## My second headline
</p>
````

I'm testing plugins compatibility for K4 but I couldn't work correctly. What am I doing wrong?

Kirby 4.0.0-rc.4
Plugin 2.0.0

**Comment by nilshoerrmann** [comment]
Can you please try this:

```php
<?= $page->text()->toTree('kirbytext')->level(3) ?>
```

Looks like the readme is outdated.

**Comment by nilshoerrmann** [comment]
General comment: This plugin will soon be deprecated and be replaced by a new implementation.

**Comment by afbora** [comment]
@nilshoerrmann Thanks. So you want to me archive it in getkirby.com plugins directory?

**Comment by nilshoerrmann** [comment]
No, not yet – thanks!
